/* ============================================================
   ELC STEM hub v2 — helper-word glosses
   The everyday instruction language of a task, in 18 languages.
   Students may tap these any time (stem-translate.js).
   The words the Vocab Hub TEACHES are not here on purpose —
   those stay locked until the student builds them.
   Teachers: add a word by adding an entry with all 18 keys.
   ============================================================ */
window.STEM_GLOSS = {
 "above": {
  "am": "በላይ",
  "ar": "فوق",
  "es": "encima (arriba)",
  "fa": "بالای",
  "fr": "au-dessus",
  "hi": "के ऊपर",
  "ja": "…より上",
  "ko": "위에",
  "ml": "മുകളിൽ",
  "ps": "پورته (له…څخه)",
  "ro": "deasupra",
  "ru": "выше (над)",
  "ta": "மேலே",
  "tl": "sa itaas",
  "ur": "اوپر",
  "vi": "ở trên",
  "zh-Hans": "在…上方",
  "zh-Hant": "在…上方"
 },
 "accurate": {
  "am": "ትክክለኛ (ልክ)",
  "ar": "دقيق",
  "es": "preciso (exacto)",
  "fa": "دقیق",
  "fr": "précis",
  "hi": "सटीक",
  "ja": "正確な",
  "ko": "정확한",
  "ml": "കൃത്യമായ",
  "ps": "دقیق",
  "ro": "precis",
  "ru": "точный",
  "ta": "துல்லியமான",
  "tl": "tumpak",
  "ur": "درست (بالکل ٹھیک)",
  "vi": "chính xác",
  "zh-Hans": "准确的",
  "zh-Hant": "準確的"
 },
 "after": {
  "am": "በኋላ",
  "ar": "بعد",
  "es": "después",
  "fa": "بعد از",
  "fr": "après",
  "hi": "के बाद",
  "ja": "…の後に",
  "ko": "후에",
  "ml": "ശേഷം",
  "ps": "وروسته",
  "ro": "după",
  "ru": "после",
  "ta": "பிறகு",
  "tl": "pagkatapos",
  "ur": "کے بعد",
  "vi": "sau",
  "zh-Hans": "之后",
  "zh-Hant": "之後"
 },
 "also": {
  "am": "እንዲሁም",
  "ar": "أيضًا",
  "es": "también",
  "fa": "همچنین",
  "fr": "aussi",
  "hi": "भी",
  "ja": "また（〜も）",
  "ko": "또한",
  "ml": "കൂടാതെ",
  "ps": "هم",
  "ro": "de asemenea",
  "ru": "также",
  "ta": "மேலும்",
  "tl": "din (rin)",
  "ur": "نیز (بھی)",
  "vi": "cũng",
  "zh-Hans": "也（还）",
  "zh-Hant": "也（還）"
 },
 "amount": {
  "am": "መጠን",
  "ar": "الكمية",
  "es": "cantidad",
  "fa": "مقدار (کمیت)",
  "fr": "quantité",
  "hi": "मात्रा",
  "ja": "量",
  "ko": "양",
  "ml": "അളവ്",
  "ps": "مقدار",
  "ro": "cantitate",
  "ru": "количество",
  "ta": "அளவு",
  "tl": "dami",
  "ur": "مقدار",
  "vi": "lượng",
  "zh-Hans": "数量",
  "zh-Hant": "數量"
 },
 "answer": {
  "am": "መልስ",
  "ar": "أجب (الإجابة)",
  "es": "respuesta",
  "fa": "پاسخ",
  "fr": "réponse",
  "hi": "उत्तर",
  "ja": "答え",
  "ko": "답",
  "ml": "ഉത്തരം",
  "ps": "ځواب",
  "ro": "răspuns",
  "ru": "ответ",
  "ta": "விடை",
  "tl": "sagot",
  "ur": "جواب",
  "vi": "đáp án (câu trả lời)",
  "zh-Hans": "答案（回答）",
  "zh-Hant": "答案（作答）"
 },
 "average": {
  "am": "አማካይ",
  "ar": "متوسط",
  "es": "promedio",
  "fa": "میانگین",
  "fr": "moyenne",
  "hi": "औसत",
  "ja": "平均",
  "ko": "평균",
  "ml": "ശരാശരി",
  "ps": "منځنی",
  "ro": "medie",
  "ru": "среднее",
  "ta": "சராசரி",
  "tl": "average (mean)",
  "ur": "اوسط",
  "vi": "trung bình",
  "zh-Hans": "平均",
  "zh-Hant": "平均"
 },
 "axis": {
  "am": "ዘንግ",
  "ar": "المحور",
  "es": "eje",
  "fa": "محور",
  "fr": "axe",
  "hi": "अक्ष",
  "ja": "軸（座標軸）",
  "ko": "축 (좌표축)",
  "ml": "അക്ഷം",
  "ps": "محور",
  "ro": "axă",
  "ru": "ось",
  "ta": "அச்சு",
  "tl": "aksis (ehe)",
  "ur": "محور",
  "vi": "trục (tọa độ)",
  "zh-Hans": "坐标轴",
  "zh-Hant": "坐標軸"
 },
 "because": {
  "am": "ምክንያቱም",
  "ar": "لأنّ",
  "es": "porque",
  "fa": "زیرا",
  "fr": "parce que",
  "hi": "क्योंकि",
  "ja": "なぜなら（〜ので）",
  "ko": "왜냐하면",
  "ml": "എന്തുകൊണ്ടെന്നാൽ",
  "ps": "ځکه چې",
  "ro": "pentru că",
  "ru": "потому что",
  "ta": "ஏனெனில்",
  "tl": "dahil",
  "ur": "کیونکہ",
  "vi": "bởi vì",
  "zh-Hans": "因为",
  "zh-Hant": "因為"
 },
 "before": {
  "am": "በፊት",
  "ar": "قبل",
  "es": "antes",
  "fa": "قبل از",
  "fr": "avant",
  "hi": "से पहले",
  "ja": "…の前に",
  "ko": "전에",
  "ml": "മുമ്പ്",
  "ps": "مخکې",
  "ro": "înainte",
  "ru": "до (перед)",
  "ta": "முன்பு",
  "tl": "bago",
  "ur": "سے پہلے",
  "vi": "trước",
  "zh-Hans": "之前",
  "zh-Hant": "之前"
 },
 "below": {
  "am": "በታች",
  "ar": "تحت",
  "es": "debajo (abajo)",
  "fa": "زیر",
  "fr": "au-dessous",
  "hi": "के नीचे",
  "ja": "…より下",
  "ko": "아래에",
  "ml": "താഴെ",
  "ps": "لاندې",
  "ro": "sub (dedesubt)",
  "ru": "ниже (под)",
  "ta": "கீழே",
  "tl": "sa ibaba",
  "ur": "نیچے",
  "vi": "ở dưới",
  "zh-Hans": "在…下方",
  "zh-Hant": "在…下方"
 },
 "between": {
  "am": "መካከል",
  "ar": "بين",
  "es": "entre",
  "fa": "بین",
  "fr": "entre",
  "hi": "के बीच",
  "ja": "…の間",
  "ko": "사이에",
  "ml": "ഇടയിൽ",
  "ps": "تر منځ",
  "ro": "între",
  "ru": "между",
  "ta": "இடையே",
  "tl": "sa pagitan",
  "ur": "کے درمیان",
  "vi": "giữa",
  "zh-Hans": "在…之间",
  "zh-Hant": "在…之間"
 },
 "calculate": {
  "am": "ማስላት",
  "ar": "يحسب",
  "es": "calcular",
  "fa": "محاسبه کردن",
  "fr": "calculer",
  "hi": "गणना करना",
  "ja": "計算する",
  "ko": "계산하다",
  "ml": "കണക്കാക്കുക",
  "ps": "محاسبه کول",
  "ro": "a calcula",
  "ru": "вычислять",
  "ta": "கணக்கிடுதல்",
  "tl": "kalkulahin",
  "ur": "حساب کرنا",
  "vi": "tính toán",
  "zh-Hans": "计算",
  "zh-Hant": "計算"
 },
 "careful": {
  "am": "ጥንቁቅ",
  "ar": "متأنٍ (بعناية)",
  "es": "cuidadoso",
  "fa": "با دقت",
  "fr": "soigneux (attentif)",
  "hi": "सावधान",
  "ja": "注意深い",
  "ko": "주의 깊은",
  "ml": "ശ്രദ്ധയോടെ",
  "ps": "په پام سره (محتاط)",
  "ro": "atent",
  "ru": "внимательный",
  "ta": "கவனமான",
  "tl": "maingat",
  "ur": "احتیاط سے",
  "vi": "cẩn thận",
  "zh-Hans": "仔细的",
  "zh-Hant": "仔細的"
 },
 "change": {
  "am": "ለውጥ",
  "ar": "تغير",
  "es": "cambio",
  "fa": "تغییر",
  "fr": "changement",
  "hi": "परिवर्तन",
  "ja": "変化",
  "ko": "변화",
  "ml": "മാറ്റം",
  "ps": "بدلون",
  "ro": "schimbare",
  "ru": "изменение",
  "ta": "மாற்றம்",
  "tl": "pagbabago",
  "ur": "تبدیلی",
  "vi": "sự biến đổi",
  "zh-Hans": "变化",
  "zh-Hant": "變化"
 },
 "check": {
  "am": "ማረጋገጥ",
  "ar": "تحقّق",
  "es": "comprobar",
  "fa": "بررسی کنید",
  "fr": "vérifier",
  "hi": "जाँचना",
  "ja": "確かめる",
  "ko": "확인하다",
  "ml": "പരിശോധിക്കുക",
  "ps": "وګورئ (تایید)",
  "ro": "a verifica",
  "ru": "проверить",
  "ta": "சரிபார்",
  "tl": "tiyakin",
  "ur": "جانچیں",
  "vi": "kiểm tra",
  "zh-Hans": "检查（核对）",
  "zh-Hant": "檢查（核對）"
 },
 "choose": {
  "am": "መምረጥ",
  "ar": "اختر",
  "es": "elegir",
  "fa": "انتخاب کنید",
  "fr": "choisir",
  "hi": "चुनना",
  "ja": "選ぶ",
  "ko": "고르다",
  "ml": "തിരഞ്ഞെടുക്കുക",
  "ps": "غوره کړئ",
  "ro": "a alege",
  "ru": "выбрать",
  "ta": "தேர்ந்தெடு",
  "tl": "piliin",
  "ur": "منتخب کریں",
  "vi": "chọn",
  "zh-Hans": "选择",
  "zh-Hant": "選擇"
 },
 "clearly": {
  "am": "በግልጽ",
  "ar": "بوضوح",
  "es": "claramente",
  "fa": "به‌روشنی",
  "fr": "clairement",
  "hi": "स्पष्ट रूप से",
  "ja": "はっきりと",
  "ko": "분명하게",
  "ml": "വ്യക്തമായി",
  "ps": "په څرګنده",
  "ro": "clar",
  "ru": "чётко (ясно)",
  "ta": "தெளிவாக",
  "tl": "malinaw",
  "ur": "واضح طور پر",
  "vi": "rõ ràng",
  "zh-Hans": "清楚地",
  "zh-Hant": "清楚地"
 },
 "compare": {
  "am": "ማወዳደር",
  "ar": "يقارن",
  "es": "comparar",
  "fa": "مقایسه کردن",
  "fr": "comparer",
  "hi": "तुलना करना",
  "ja": "比較する",
  "ko": "비교하다",
  "ml": "താരതമ്യം ചെയ്യുക",
  "ps": "پرتله کول",
  "ro": "a compara",
  "ru": "сравнивать",
  "ta": "ஒப்பிடு",
  "tl": "ihambing",
  "ur": "موازنہ کرنا",
  "vi": "so sánh",
  "zh-Hans": "比较",
  "zh-Hant": "比較"
 },
 "complete": {
  "am": "ማጠናቀቅ",
  "ar": "أكمل",
  "es": "completar",
  "fa": "کامل کنید",
  "fr": "compléter",
  "hi": "पूरा करना",
  "ja": "完成させる",
  "ko": "완성하다",
  "ml": "പൂർത്തിയാക്കുക",
  "ps": "بشپړ کړئ",
  "ro": "a completa",
  "ru": "завершить",
  "ta": "பூர்த்தி செய்",
  "tl": "kumpletuhin",
  "ur": "مکمل کریں",
  "vi": "hoàn thành",
  "zh-Hans": "完成",
  "zh-Hant": "完成"
 },
 "correct": {
  "am": "ትክክል",
  "ar": "صحيح",
  "es": "correcto",
  "fa": "درست",
  "fr": "correct (juste)",
  "hi": "सही",
  "ja": "正しい",
  "ko": "맞는 (옳은)",
  "ml": "ശരിയായ",
  "ps": "سم (صحیح)",
  "ro": "corect",
  "ru": "правильный",
  "ta": "சரியான",
  "tl": "tama",
  "ur": "صحیح",
  "vi": "đúng",
  "zh-Hans": "正确的",
  "zh-Hant": "正確的"
 },
 "curve": {
  "am": "ጥምዝ መስመር",
  "ar": "المنحنى",
  "es": "curva",
  "fa": "منحنی",
  "fr": "courbe",
  "hi": "वक्र",
  "ja": "曲線",
  "ko": "곡선",
  "ml": "വക്രരേഖ",
  "ps": "کږه کرښه",
  "ro": "curbă",
  "ru": "кривая",
  "ta": "வளைகோடு",
  "tl": "kurba",
  "ur": "منحنی خط",
  "vi": "đường cong",
  "zh-Hans": "曲线",
  "zh-Hant": "曲線"
 },
 "decrease": {
  "am": "መቀነስ",
  "ar": "ينقص (نقصان)",
  "es": "disminuir",
  "fa": "کاهش",
  "fr": "diminuer",
  "hi": "घटना",
  "ja": "減少する",
  "ko": "감소하다",
  "ml": "കുറയുക",
  "ps": "کموالی",
  "ro": "a scădea",
  "ru": "уменьшаться",
  "ta": "குறை",
  "tl": "bumaba (bawas)",
  "ur": "کمی",
  "vi": "giảm",
  "zh-Hans": "减少",
  "zh-Hant": "減少"
 },
 "describe": {
  "am": "መግለጽ",
  "ar": "يصف",
  "es": "describir",
  "fa": "توصیف کردن",
  "fr": "décrire",
  "hi": "वर्णन करना",
  "ja": "述べる（記述する）",
  "ko": "묘사하다",
  "ml": "വിവരിക്കുക",
  "ps": "بیانول",
  "ro": "a descrie",
  "ru": "описывать",
  "ta": "விவரி",
  "tl": "ilarawan",
  "ur": "بیان کرنا",
  "vi": "mô tả",
  "zh-Hans": "描述",
  "zh-Hant": "描述"
 },
 "difference": {
  "am": "ልዩነት",
  "ar": "الفرق",
  "es": "diferencia",
  "fa": "تفاضل",
  "fr": "différence",
  "hi": "अंतर",
  "ja": "差",
  "ko": "차",
  "ml": "വ്യത്യാസം",
  "ps": "توپیر",
  "ro": "diferență",
  "ru": "разность",
  "ta": "வித்தியாசம்",
  "tl": "diperensya",
  "ur": "فرق",
  "vi": "hiệu",
  "zh-Hans": "差",
  "zh-Hant": "差"
 },
 "distance": {
  "am": "ርቀት",
  "ar": "المسافة",
  "es": "distancia",
  "fa": "مسافت",
  "fr": "distance",
  "hi": "दूरी",
  "ja": "距離",
  "ko": "거리",
  "ml": "ദൂരം",
  "ps": "واټن",
  "ro": "distanță",
  "ru": "расстояние",
  "ta": "தூரம்",
  "tl": "distansya (layo)",
  "ur": "فاصلہ",
  "vi": "quãng đường",
  "zh-Hans": "距离",
  "zh-Hant": "距離"
 },
 "draw": {
  "am": "መሳል",
  "ar": "ارسم",
  "es": "dibujar (trazar)",
  "fa": "رسم کنید",
  "fr": "tracer (dessiner)",
  "hi": "बनाना (आरेख)",
  "ja": "描く（図を）",
  "ko": "그리다",
  "ml": "വരയ്ക്കുക",
  "ps": "رسم کړئ",
  "ro": "a desena",
  "ru": "начертить",
  "ta": "வரை",
  "tl": "iguhit",
  "ur": "بنائیں (شکل)",
  "vi": "vẽ",
  "zh-Hans": "画（图）",
  "zh-Hant": "畫（作圖）"
 },
 "during": {
  "am": "በ…ጊዜ",
  "ar": "خلال",
  "es": "durante",
  "fa": "در طول",
  "fr": "pendant",
  "hi": "के दौरान",
  "ja": "…の間に",
  "ko": "동안",
  "ml": "സമയത്ത്",
  "ps": "پر مهال",
  "ro": "în timpul",
  "ru": "во время",
  "ta": "போது",
  "tl": "habang",
  "ur": "کے دوران",
  "vi": "trong khi",
  "zh-Hans": "在…期间",
  "zh-Hant": "在…期間"
 },
 "each": {
  "am": "እያንዳንዱ",
  "ar": "كل واحد",
  "es": "cada uno",
  "fa": "هر یک",
  "fr": "chaque",
  "hi": "प्रत्येक",
  "ja": "それぞれ",
  "ko": "각각",
  "ml": "ഓരോ",
  "ps": "هر یو",
  "ro": "fiecare",
  "ru": "каждый",
  "ta": "ஒவ்வொரு",
  "tl": "bawat isa",
  "ur": "ہر ایک",
  "vi": "mỗi",
  "zh-Hans": "每个（各自）",
  "zh-Hant": "每個（各自）"
 },
 "estimate": {
  "am": "ግምት",
  "ar": "تقدير",
  "es": "estimación",
  "fa": "تخمین / برآورد",
  "fr": "estimation",
  "hi": "अनुमान",
  "ja": "概算",
  "ko": "어림 / 추정",
  "ml": "ഏകദേശ കണക്ക്",
  "ps": "اټکل",
  "ro": "estimare",
  "ru": "оценка",
  "ta": "மதிப்பீடு",
  "tl": "tantiya",
  "ur": "تخمینہ / اندازہ",
  "vi": "ước lượng",
  "zh-Hans": "估计",
  "zh-Hant": "估計"
 },
 "every": {
  "am": "ሁሉም",
  "ar": "كل",
  "es": "cada (todos)",
  "fa": "هر",
  "fr": "tous (chaque)",
  "hi": "हर",
  "ja": "すべての",
  "ko": "모든",
  "ml": "എല്ലാ",
  "ps": "هر",
  "ro": "fiecare (toți)",
  "ru": "все (каждый)",
  "ta": "எல்லா",
  "tl": "lahat ng",
  "ur": "ہر",
  "vi": "mọi",
  "zh-Hans": "每一个（全部）",
  "zh-Hant": "每一個（全部）"
 },
 "exactly": {
  "am": "በትክክል",
  "ar": "بالضبط",
  "es": "exactamente",
  "fa": "دقیقاً",
  "fr": "exactement",
  "hi": "ठीक-ठीक",
  "ja": "ちょうど（正確に）",
  "ko": "정확히",
  "ml": "കൃത്യമായി",
  "ps": "دقیقاً",
  "ro": "exact",
  "ru": "точно",
  "ta": "சரியாக",
  "tl": "eksakto",
  "ur": "بالکل ٹھیک",
  "vi": "chính xác (đúng bằng)",
  "zh-Hans": "恰好（精确地）",
  "zh-Hant": "恰好（精確地）"
 },
 "example": {
  "am": "ምሳሌ",
  "ar": "مثال",
  "es": "ejemplo",
  "fa": "مثال",
  "fr": "exemple",
  "hi": "उदाहरण",
  "ja": "例",
  "ko": "예",
  "ml": "ഉദാഹരണം",
  "ps": "بېلګه",
  "ro": "exemplu",
  "ru": "пример",
  "ta": "எடுத்துக்காட்டு",
  "tl": "halimbawa",
  "ur": "مثال",
  "vi": "ví dụ",
  "zh-Hans": "例子",
  "zh-Hant": "例子"
 },
 "explain": {
  "am": "ማብራራት",
  "ar": "يشرح",
  "es": "explicar",
  "fa": "توضیح دادن",
  "fr": "expliquer",
  "hi": "समझाना",
  "ja": "説明する",
  "ko": "설명하다",
  "ml": "വിശദീകരിക്കുക",
  "ps": "تشریح کول",
  "ro": "a explica",
  "ru": "объяснять",
  "ta": "விளக்கு",
  "tl": "ipaliwanag",
  "ur": "وضاحت کرنا",
  "vi": "giải thích",
  "zh-Hans": "解释",
  "zh-Hant": "解釋"
 },
 "finally": {
  "am": "በመጨረሻ",
  "ar": "أخيرًا",
  "es": "por último",
  "fa": "در پایان",
  "fr": "enfin",
  "hi": "अंत में",
  "ja": "最後に",
  "ko": "마지막으로",
  "ml": "അവസാനമായി",
  "ps": "په پای کې",
  "ro": "în final",
  "ru": "наконец",
  "ta": "இறுதியாக",
  "tl": "sa wakas",
  "ur": "آخر میں",
  "vi": "cuối cùng",
  "zh-Hans": "最后（最终）",
  "zh-Hant": "最後（最終）"
 },
 "find": {
  "am": "ማግኘት",
  "ar": "أوجد",
  "es": "hallar",
  "fa": "یافتن",
  "fr": "trouver",
  "hi": "ज्ञात करना",
  "ja": "求める",
  "ko": "구하다",
  "ml": "കണ്ടെത്തുക",
  "ps": "موندل",
  "ro": "a afla",
  "ru": "найти",
  "ta": "காண்",
  "tl": "hanapin",
  "ur": "معلوم کرنا",
  "vi": "tìm",
  "zh-Hans": "求",
  "zh-Hant": "求"
 },
 "first": {
  "am": "መጀመሪያ",
  "ar": "أولًا",
  "es": "primero",
  "fa": "ابتدا",
  "fr": "d'abord",
  "hi": "सबसे पहले",
  "ja": "最初に",
  "ko": "먼저",
  "ml": "ആദ്യം",
  "ps": "لومړی",
  "ro": "mai întâi",
  "ru": "сначала",
  "ta": "முதலில்",
  "tl": "una",
  "ur": "سب سے پہلے",
  "vi": "đầu tiên",
  "zh-Hans": "首先",
  "zh-Hant": "首先"
 },
 "fraction": {
  "am": "ክፍልፋይ",
  "ar": "كسر",
  "es": "fracción",
  "fa": "کسر",
  "fr": "fraction",
  "hi": "भिन्न",
  "ja": "分数",
  "ko": "분수",
  "ml": "ഭിന്നസംഖ്യ",
  "ps": "کسر",
  "ro": "fracție",
  "ru": "дробь",
  "ta": "பின்னம்",
  "tl": "praksyon",
  "ur": "کسر",
  "vi": "phân số",
  "zh-Hans": "分数",
  "zh-Hant": "分數"
 },
 "graph": {
  "am": "ግራፍ",
  "ar": "رسم بياني",
  "es": "gráfico",
  "fa": "نمودار",
  "fr": "graphique",
  "hi": "ग्राफ़",
  "ja": "グラフ",
  "ko": "그래프",
  "ml": "ഗ്രാഫ്",
  "ps": "ګراف",
  "ro": "grafic",
  "ru": "график",
  "ta": "வரைபடம்",
  "tl": "grap",
  "ur": "گراف",
  "vi": "đồ thị",
  "zh-Hans": "图象（图表）",
  "zh-Hant": "圖象（圖表）"
 },
 "however": {
  "am": "ሆኖም ግን",
  "ar": "لكن (غير أنّ)",
  "es": "sin embargo",
  "fa": "با این حال",
  "fr": "cependant",
  "hi": "हालाँकि",
  "ja": "しかし",
  "ko": "그러나",
  "ml": "എന്നാൽ",
  "ps": "خو (سره له دې)",
  "ro": "însă (totuși)",
  "ru": "однако",
  "ta": "எனினும்",
  "tl": "gayunpaman",
  "ur": "تاہم",
  "vi": "tuy nhiên",
  "zh-Hans": "然而（但是）",
  "zh-Hant": "然而（但是）"
 },
 "identify": {
  "am": "መለየት",
  "ar": "يحدد",
  "es": "identificar",
  "fa": "شناسایی کردن",
  "fr": "identifier",
  "hi": "पहचानना",
  "ja": "特定する",
  "ko": "식별하다",
  "ml": "തിരിച്ചറിയുക",
  "ps": "پیژندل",
  "ro": "a identifica",
  "ru": "определять",
  "ta": "அடையாளம் காண்",
  "tl": "tukuyin",
  "ur": "شناخت کرنا",
  "vi": "xác định",
  "zh-Hans": "识别",
  "zh-Hant": "識別"
 },
 "improve": {
  "am": "ማሻሻል",
  "ar": "حسّن",
  "es": "mejorar",
  "fa": "بهبود دهید",
  "fr": "améliorer",
  "hi": "सुधारना",
  "ja": "改善する",
  "ko": "개선하다",
  "ml": "മെച്ചപ്പെടുത്തുക",
  "ps": "ښه کړئ",
  "ro": "a îmbunătăți",
  "ru": "улучшить",
  "ta": "மேம்படுத்து",
  "tl": "pagbutihin",
  "ur": "بہتر بنائیں",
  "vi": "cải thiện",
  "zh-Hans": "改进",
  "zh-Hant": "改進"
 },
 "increase": {
  "am": "መጨመር",
  "ar": "يزداد (زيادة)",
  "es": "aumentar",
  "fa": "افزایش",
  "fr": "augmenter",
  "hi": "बढ़ना",
  "ja": "増加する",
  "ko": "증가하다",
  "ml": "വർധിക്കുക",
  "ps": "زیاتوالی",
  "ro": "a crește",
  "ru": "увеличиваться",
  "ta": "அதிகரி",
  "tl": "tumaas (dagdag)",
  "ur": "اضافہ",
  "vi": "tăng",
  "zh-Hans": "增加",
  "zh-Hant": "增加"
 },
 "inside": {
  "am": "ውስጥ",
  "ar": "داخل",
  "es": "dentro",
  "fa": "داخل",
  "fr": "à l'intérieur",
  "hi": "के अंदर",
  "ja": "内側（中）",
  "ko": "안에",
  "ml": "അകത്ത്",
  "ps": "دننه",
  "ro": "în interior",
  "ru": "внутри",
  "ta": "உள்ளே",
  "tl": "sa loob",
  "ur": "اندر",
  "vi": "bên trong",
  "zh-Hans": "在…里面",
  "zh-Hant": "在…裡面"
 },
 "label": {
  "am": "መሰየም",
  "ar": "سمِّ (اكتب الاسم)",
  "es": "rotular",
  "fa": "برچسب بزنید",
  "fr": "légender",
  "hi": "नाम लिखना",
  "ja": "ラベルを付ける",
  "ko": "이름 붙이다",
  "ml": "പേരെഴുതുക",
  "ps": "نوم ولیکئ",
  "ro": "a eticheta",
  "ru": "подписать",
  "ta": "பெயரிடு",
  "tl": "lagyan ng label",
  "ur": "نام لکھیں",
  "vi": "ghi nhãn",
  "zh-Hans": "标注",
  "zh-Hant": "標示"
 },
 "last": {
  "am": "የመጨረሻው",
  "ar": "الأخير",
  "es": "último",
  "fa": "آخرین",
  "fr": "dernier",
  "hi": "अंतिम",
  "ja": "最後の",
  "ko": "마지막",
  "ml": "അവസാനത്തെ",
  "ps": "وروستی",
  "ro": "ultimul",
  "ru": "последний",
  "ta": "கடைசி",
  "tl": "huli",
  "ur": "آخری",
  "vi": "sau cùng",
  "zh-Hans": "最后一个",
  "zh-Hant": "最後一個"
 },
 "line": {
  "am": "መስመር",
  "ar": "الخط",
  "es": "recta (línea)",
  "fa": "خط",
  "fr": "droite (ligne)",
  "hi": "रेखा",
  "ja": "線（直線）",
  "ko": "선 (직선)",
  "ml": "രേഖ",
  "ps": "کرښه",
  "ro": "linie (dreaptă)",
  "ru": "линия (прямая)",
  "ta": "கோடு",
  "tl": "linya (guhit)",
  "ur": "خط",
  "vi": "đường thẳng",
  "zh-Hans": "线（直线）",
  "zh-Hant": "線（直線）"
 },
 "list": {
  "am": "መዘርዘር",
  "ar": "يسرد",
  "es": "enumerar",
  "fa": "فهرست کردن",
  "fr": "énumérer",
  "hi": "सूचीबद्ध करना",
  "ja": "列挙する",
  "ko": "나열하다",
  "ml": "പട്ടികപ്പെടുത്തുക",
  "ps": "لیست کول",
  "ro": "a enumera",
  "ru": "перечислять",
  "ta": "பட்டியலிடு",
  "tl": "ilista",
  "ur": "فہرست بنانا",
  "vi": "liệt kê",
  "zh-Hans": "列出",
  "zh-Hant": "列出"
 },
 "measure": {
  "am": "መለካት",
  "ar": "قِس (قياس)",
  "es": "medir",
  "fa": "اندازه بگیرید",
  "fr": "mesurer",
  "hi": "मापना",
  "ja": "測定する",
  "ko": "측정하다",
  "ml": "അളക്കുക",
  "ps": "اندازه کړئ",
  "ro": "a măsura",
  "ru": "измерить",
  "ta": "அளவிடு",
  "tl": "sukatin",
  "ur": "پیمائش کریں",
  "vi": "đo",
  "zh-Hans": "测量",
  "zh-Hant": "測量"
 },
 "method": {
  "am": "ዘዴ",
  "ar": "الطريقة",
  "es": "método",
  "fa": "روش",
  "fr": "méthode",
  "hi": "विधि",
  "ja": "方法",
  "ko": "방법",
  "ml": "രീതി",
  "ps": "طریقه",
  "ro": "metodă",
  "ru": "метод",
  "ta": "முறை",
  "tl": "paraan",
  "ur": "طریقہ",
  "vi": "phương pháp",
  "zh-Hans": "方法（步骤）",
  "zh-Hant": "方法（步驟）"
 },
 "next": {
  "am": "ቀጥሎ",
  "ar": "التالي",
  "es": "siguiente",
  "fa": "بعدی",
  "fr": "ensuite",
  "hi": "अगला",
  "ja": "次に",
  "ko": "다음으로",
  "ml": "അടുത്തത്",
  "ps": "راتلونکی",
  "ro": "în continuare",
  "ru": "следующий",
  "ta": "அடுத்து",
  "tl": "susunod",
  "ur": "اگلا",
  "vi": "tiếp theo",
  "zh-Hans": "接下来",
  "zh-Hant": "接下來"
 },
 "number": {
  "am": "ቁጥር",
  "ar": "العدد",
  "es": "número",
  "fa": "عدد",
  "fr": "nombre",
  "hi": "संख्या",
  "ja": "数",
  "ko": "수 (숫자)",
  "ml": "സംഖ്യ",
  "ps": "شمېره (عدد)",
  "ro": "număr",
  "ru": "число",
  "ta": "எண்",
  "tl": "bilang",
  "ur": "عدد",
  "vi": "số",
  "zh-Hans": "数（数字）",
  "zh-Hant": "數（數字）"
 },
 "outside": {
  "am": "ውጭ",
  "ar": "خارج",
  "es": "fuera",
  "fa": "خارج",
  "fr": "à l'extérieur",
  "hi": "के बाहर",
  "ja": "外側（外）",
  "ko": "밖에",
  "ml": "പുറത്ത്",
  "ps": "بهر",
  "ro": "în exterior",
  "ru": "снаружи",
  "ta": "வெளியே",
  "tl": "sa labas",
  "ur": "باہر",
  "vi": "bên ngoài",
  "zh-Hans": "在…外面",
  "zh-Hant": "在…外面"
 },
 "percentage": {
  "am": "መቶኛ",
  "ar": "النسبة المئوية",
  "es": "porcentaje",
  "fa": "درصد",
  "fr": "pourcentage",
  "hi": "प्रतिशत",
  "ja": "百分率（％）",
  "ko": "백분율",
  "ml": "ശതമാനം",
  "ps": "سلنه",
  "ro": "procent",
  "ru": "процент",
  "ta": "சதவீதம்",
  "tl": "porsyento",
  "ur": "فیصد",
  "vi": "phần trăm",
  "zh-Hans": "百分比",
  "zh-Hant": "百分比"
 },
 "point": {
  "am": "ነጥብ",
  "ar": "النقطة",
  "es": "punto",
  "fa": "نقطه",
  "fr": "point",
  "hi": "बिंदु",
  "ja": "点（グラフ上）",
  "ko": "점 (그래프의)",
  "ml": "ബിന്ദു",
  "ps": "ټکی (نقطه)",
  "ro": "punct",
  "ru": "точка",
  "ta": "புள்ளி",
  "tl": "punto",
  "ur": "نقطہ",
  "vi": "điểm (trên đồ thị)",
  "zh-Hans": "点（图上）",
  "zh-Hant": "點（圖上）"
 },
 "practice": {
  "am": "ልምምድ",
  "ar": "تدريب",
  "es": "práctica",
  "fa": "تمرین",
  "fr": "entraînement",
  "hi": "अभ्यास",
  "ja": "練習",
  "ko": "연습",
  "ml": "പരിശീലനം",
  "ps": "تمرین",
  "ro": "exercițiu",
  "ru": "упражнение",
  "ta": "பயிற்சி",
  "tl": "pagsasanay",
  "ur": "مشق",
  "vi": "luyện tập",
  "zh-Hans": "练习",
  "zh-Hant": "練習"
 },
 "predict": {
  "am": "መተንበይ",
  "ar": "توقّع",
  "es": "predecir",
  "fa": "پیش‌بینی کنید",
  "fr": "prédire",
  "hi": "पूर्वानुमान लगाना",
  "ja": "予測する",
  "ko": "예측하다",
  "ml": "പ്രവചിക്കുക",
  "ps": "وړاندوینه وکړئ",
  "ro": "a prezice",
  "ru": "предсказать",
  "ta": "முன்கணிக்க",
  "tl": "hulaan",
  "ur": "پیش گوئی کریں",
  "vi": "dự đoán",
  "zh-Hans": "预测",
  "zh-Hant": "預測"
 },
 "question": {
  "am": "ጥያቄ",
  "ar": "السؤال",
  "es": "pregunta",
  "fa": "سؤال",
  "fr": "question",
  "hi": "प्रश्न",
  "ja": "問題",
  "ko": "문제",
  "ml": "ചോദ്യം",
  "ps": "پوښتنه",
  "ro": "întrebare",
  "ru": "вопрос",
  "ta": "வினா (கேள்வி)",
  "tl": "tanong",
  "ur": "سوال",
  "vi": "câu hỏi",
  "zh-Hans": "问题（题目）",
  "zh-Hant": "題目（問題）"
 },
 "read": {
  "am": "ማንበብ (ግራፍ)",
  "ar": "اقرأ (الرسم)",
  "es": "leer (la gráfica)",
  "fa": "بخوانید (نمودار)",
  "fr": "lire (un graphique)",
  "hi": "पढ़ना (ग्राफ़)",
  "ja": "読み取る（グラフ）",
  "ko": "읽다 (그래프)",
  "ml": "വായിക്കുക (ഗ്രാഫ്)",
  "ps": "ولولئ (ګراف)",
  "ro": "a citi (graficul)",
  "ru": "читать (график)",
  "ta": "படி (வரைபடம்)",
  "tl": "basahin (grap)",
  "ur": "پڑھیں (گراف)",
  "vi": "đọc (biểu đồ)",
  "zh-Hans": "读取（图表）",
  "zh-Hant": "判讀（圖表）"
 },
 "reason": {
  "am": "ምክንያት",
  "ar": "السبب",
  "es": "razón",
  "fa": "دلیل",
  "fr": "raison",
  "hi": "कारण",
  "ja": "理由",
  "ko": "이유",
  "ml": "കാരണം",
  "ps": "دلیل",
  "ro": "motiv",
  "ru": "причина",
  "ta": "காரணம்",
  "tl": "dahilan",
  "ur": "وجہ",
  "vi": "lý do",
  "zh-Hans": "原因（理由）",
  "zh-Hant": "原因（理由）"
 },
 "record": {
  "am": "መመዝገብ",
  "ar": "سجّل",
  "es": "registrar (anotar)",
  "fa": "ثبت کنید",
  "fr": "noter (relever)",
  "hi": "दर्ज करना",
  "ja": "記録する",
  "ko": "기록하다",
  "ml": "രേഖപ്പെടുത്തുക",
  "ps": "ثبت کړئ",
  "ro": "a înregistra",
  "ru": "записать",
  "ta": "பதிவு செய்",
  "tl": "itala",
  "ur": "درج کریں",
  "vi": "ghi lại",
  "zh-Hans": "记录",
  "zh-Hant": "記錄"
 },
 "result": {
  "am": "ውጤት",
  "ar": "النتيجة",
  "es": "resultado",
  "fa": "نتیجه",
  "fr": "résultat",
  "hi": "परिणाम",
  "ja": "結果",
  "ko": "결과",
  "ml": "ഫലം",
  "ps": "پایله",
  "ro": "rezultat",
  "ru": "результат",
  "ta": "முடிவு",
  "tl": "resulta",
  "ur": "نتیجہ",
  "vi": "kết quả",
  "zh-Hans": "结果",
  "zh-Hant": "結果"
 },
 "review": {
  "am": "መከለስ",
  "ar": "راجِع",
  "es": "repasar",
  "fa": "مرور کنید",
  "fr": "réviser",
  "hi": "दोहराना",
  "ja": "復習する",
  "ko": "복습하다",
  "ml": "പുനരവലോകനം ചെയ്യുക",
  "ps": "بیاکتنه وکړئ",
  "ro": "a recapitula",
  "ru": "повторить",
  "ta": "மறுபார்வை செய்",
  "tl": "repasuhin",
  "ur": "دہرائیں",
  "vi": "ôn tập",
  "zh-Hans": "复习（回顾）",
  "zh-Hant": "複習（回顧）"
 },
 "revise": {
  "am": "ማረም (ማሻሻል)",
  "ar": "نقّح (عدّل)",
  "es": "corregir (revisar)",
  "fa": "بازنگری کنید",
  "fr": "corriger (revoir)",
  "hi": "संशोधन करना",
  "ja": "修正する（見直す）",
  "ko": "수정하다",
  "ml": "തിരുത്തുക",
  "ps": "سمون ورکړئ",
  "ro": "a revizui",
  "ru": "исправить (доработать)",
  "ta": "திருத்தி எழுது",
  "tl": "baguhin (ayusin)",
  "ur": "نظرثانی کریں",
  "vi": "sửa lại",
  "zh-Hans": "修改（订正）",
  "zh-Hant": "修改（訂正）"
 },
 "roughly": {
  "am": "በግምት",
  "ar": "تقريبًا",
  "es": "aproximadamente",
  "fa": "تقریباً",
  "fr": "environ",
  "hi": "लगभग",
  "ja": "おおよそ",
  "ko": "대략",
  "ml": "ഏകദേശം",
  "ps": "نږدې (تقریباً)",
  "ro": "aproximativ",
  "ru": "примерно",
  "ta": "தோராயமாக",
  "tl": "humigit-kumulang",
  "ur": "تقریباً",
  "vi": "khoảng (ước chừng)",
  "zh-Hans": "大约（粗略）",
  "zh-Hant": "大約（粗略）"
 },
 "shape": {
  "am": "ቅርፅ",
  "ar": "الشكل",
  "es": "figura (forma)",
  "fa": "شکل",
  "fr": "figure (forme)",
  "hi": "आकृति",
  "ja": "図形",
  "ko": "도형",
  "ml": "ആകൃതി",
  "ps": "شکل",
  "ro": "formă (figură)",
  "ru": "фигура (форма)",
  "ta": "வடிவம்",
  "tl": "hugis",
  "ur": "شکل",
  "vi": "hình",
  "zh-Hans": "图形（形状）",
  "zh-Hant": "圖形（形狀）"
 },
 "show": {
  "am": "አሳይ",
  "ar": "بيّن",
  "es": "mostrar",
  "fa": "نشان دادن",
  "fr": "montrer",
  "hi": "दिखाना",
  "ja": "示す",
  "ko": "보이다",
  "ml": "കാണിക്കുക",
  "ps": "ښودل",
  "ro": "a arăta",
  "ru": "показать",
  "ta": "காட்டு",
  "tl": "ipakita",
  "ur": "دکھانا",
  "vi": "chỉ ra",
  "zh-Hans": "展示（显示）",
  "zh-Hant": "展示（顯示）"
 },
 "solve": {
  "am": "መፍታት",
  "ar": "يحل",
  "es": "resolver",
  "fa": "حل کردن",
  "fr": "résoudre",
  "hi": "हल करना",
  "ja": "解く",
  "ko": "풀다",
  "ml": "പരിഹരിക്കുക",
  "ps": "حل کول",
  "ro": "a rezolva",
  "ru": "решать",
  "ta": "தீர்த்தல்",
  "tl": "lutasin",
  "ur": "حل کرنا",
  "vi": "giải",
  "zh-Hans": "解",
  "zh-Hant": "解"
 },
 "speed": {
  "am": "ፍጥነት",
  "ar": "السرعة",
  "es": "rapidez (velocidad)",
  "fa": "سرعت",
  "fr": "vitesse",
  "hi": "चाल",
  "ja": "速さ",
  "ko": "속력",
  "ml": "വേഗം",
  "ps": "سرعت",
  "ro": "viteză",
  "ru": "скорость",
  "ta": "வேகம்",
  "tl": "bilis",
  "ur": "رفتار",
  "vi": "tốc độ",
  "zh-Hans": "速率",
  "zh-Hant": "速率"
 },
 "state": {
  "am": "መጥቀስ (መጻፍ)",
  "ar": "اذكر (اكتب)",
  "es": "indicar",
  "fa": "ذکر کنید (بنویسید)",
  "fr": "indiquer",
  "hi": "बताना (लिखना)",
  "ja": "書き出す（答える）",
  "ko": "답을 쓰다 (말하다)",
  "ml": "പറയുക (എഴുതുക)",
  "ps": "څرګند کړئ (ولیکئ)",
  "ro": "a preciza (a indica)",
  "ru": "указать",
  "ta": "குறிப்பிடு (எழுது)",
  "tl": "isaad (isulat)",
  "ur": "بتائیں (لکھیں)",
  "vi": "nêu ra",
  "zh-Hans": "写出",
  "zh-Hant": "寫出"
 },
 "table": {
  "am": "ሠንጠረዥ",
  "ar": "الجدول",
  "es": "tabla (de datos)",
  "fa": "جدول",
  "fr": "tableau",
  "hi": "सारणी (तालिका)",
  "ja": "表（データ）",
  "ko": "표 (자료)",
  "ml": "പട്ടിക",
  "ps": "جدول",
  "ro": "tabel",
  "ru": "таблица",
  "ta": "அட்டவணை",
  "tl": "talahanayan",
  "ur": "جدول",
  "vi": "bảng (số liệu)",
  "zh-Hans": "表格（数据）",
  "zh-Hant": "表格（資料）"
 },
 "then": {
  "am": "ከዚያ",
  "ar": "ثم",
  "es": "luego",
  "fa": "سپس",
  "fr": "puis",
  "hi": "फिर",
  "ja": "それから",
  "ko": "그다음에",
  "ml": "പിന്നെ",
  "ps": "بیا",
  "ro": "apoi",
  "ru": "затем",
  "ta": "பின்னர்",
  "tl": "tapos (saka)",
  "ur": "پھر",
  "vi": "sau đó",
  "zh-Hans": "然后",
  "zh-Hant": "然後"
 },
 "therefore": {
  "am": "ስለዚህ",
  "ar": "لذلك",
  "es": "por lo tanto",
  "fa": "بنابراین",
  "fr": "donc",
  "hi": "इसलिए",
  "ja": "したがって",
  "ko": "그러므로",
  "ml": "അതിനാൽ",
  "ps": "نو ځکه",
  "ro": "prin urmare",
  "ru": "поэтому",
  "ta": "எனவே",
  "tl": "kaya (samakatuwid)",
  "ur": "اس لیے",
  "vi": "do đó",
  "zh-Hans": "因此",
  "zh-Hant": "因此"
 },
 "time": {
  "am": "ጊዜ",
  "ar": "الزمن",
  "es": "tiempo",
  "fa": "زمان",
  "fr": "temps",
  "hi": "समय",
  "ja": "時間",
  "ko": "시간",
  "ml": "സമയം",
  "ps": "وخت",
  "ro": "timp",
  "ru": "время",
  "ta": "நேரம்",
  "tl": "oras",
  "ur": "وقت",
  "vi": "thời gian",
  "zh-Hans": "时间",
  "zh-Hant": "時間"
 },
 "total": {
  "am": "ድምር",
  "ar": "المجموع",
  "es": "total",
  "fa": "مجموع",
  "fr": "total",
  "hi": "कुल योग",
  "ja": "合計",
  "ko": "합계",
  "ml": "ആകെത്തുക",
  "ps": "ټول (مجموعه)",
  "ro": "total",
  "ru": "итого (сумма)",
  "ta": "மொத்தம்",
  "tl": "kabuuan",
  "ur": "کل (میزان)",
  "vi": "tổng",
  "zh-Hans": "总数（合计）",
  "zh-Hant": "總數（合計）"
 },
 "unit": {
  "am": "መለኪያ አሃድ",
  "ar": "الوحدة",
  "es": "unidad",
  "fa": "واحد",
  "fr": "unité",
  "hi": "इकाई",
  "ja": "単位",
  "ko": "단위",
  "ml": "ഏകകം (യൂണിറ്റ്)",
  "ps": "واحد",
  "ro": "unitate (de măsură)",
  "ru": "единица (измерения)",
  "ta": "அலகு",
  "tl": "yunit",
  "ur": "اکائی",
  "vi": "đơn vị",
  "zh-Hans": "单位",
  "zh-Hant": "單位"
 },
 "value": {
  "am": "ዋጋ",
  "ar": "قيمة",
  "es": "valor",
  "fa": "مقدار (ارزش عددی)",
  "fr": "valeur",
  "hi": "मान",
  "ja": "値",
  "ko": "값",
  "ml": "മൂല്യം",
  "ps": "ارزښت",
  "ro": "valoare",
  "ru": "значение",
  "ta": "மதிப்பு",
  "tl": "halaga",
  "ur": "قدر",
  "vi": "giá trị",
  "zh-Hans": "值",
  "zh-Hant": "值"
 },
 "write": {
  "am": "መጻፍ",
  "ar": "اكتب",
  "es": "escribir",
  "fa": "بنویسید",
  "fr": "écrire",
  "hi": "लिखना",
  "ja": "書く",
  "ko": "쓰다",
  "ml": "എഴുതുക",
  "ps": "ولیکئ",
  "ro": "a scrie",
  "ru": "написать",
  "ta": "எழுது",
  "tl": "isulat",
  "ur": "لکھیں",
  "vi": "viết",
  "zh-Hans": "写",
  "zh-Hant": "寫"
 },
 "wrong": {
  "am": "ስህተት",
  "ar": "خطأ",
  "es": "incorrecto",
  "fa": "نادرست",
  "fr": "faux (incorrect)",
  "hi": "गलत",
  "ja": "間違っている",
  "ko": "틀린",
  "ml": "തെറ്റായ",
  "ps": "غلط",
  "ro": "greșit",
  "ru": "неправильный",
  "ta": "தவறான",
  "tl": "mali",
  "ur": "غلط",
  "vi": "sai",
  "zh-Hans": "错误的",
  "zh-Hant": "錯誤的"
 }
};
